server:
  port: 8080
 
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/security
    username: pmguser
    password: pmgk1234
    driver-class-name: org.mariadb.jdbc.Driver
  
# Mapper Xml Location
mybatis:
  mapper-locations:
  - classpath:mapper/**/*.xml
  