server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
 
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/security
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
jwt:
  issuer: localhost0323@gmail.com
  secret_key: hostlocal8080@!
